Check code-style:
    image: php:8.1-cli
    before_script:
        - apt-get update
        - apt-get install zip unzip
        - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        - php composer-setup.php
        - php -r "unlink('composer-setup.php');"
    script:
        - php composer.phar install
        - php composer.phar code-style
    cache:
        paths:
            - composer.phar
            - vendor/
    only:
        - Setup_CI

Run tests:
    image: php:8.1-cli
    variables:
        POSTGRES_DB: laravel_filter_builder
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
    services:
        - postgres:latest
    before_script:
        - apt update
        - apt-get install -y gnupg gosu curl ca-certificates zip unzip python2
        - mkdir -p ~/.gnupg
        - chmod 600 ~/.gnupg
        - echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf
        - echo "keyserver hkp://keyserver.ubuntu.com:80" >> ~/.gnupg/dirmngr.conf
        - gpg --recv-key 0x14aa40ec0831756756d7f66c4f4ea0aae5267a6c
        - gpg --export 0x14aa40ec0831756756d7f66c4f4ea0aae5267a6c > /usr/share/keyrings/ppa_ondrej_php.gpg
        - echo "deb [signed-by=/usr/share/keyrings/ppa_ondrej_php.gpg] https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy main" > /etc/apt/sources.list.d/ppa_ondrej_php.list
        - apt-get update
        - apt-get install zip unzip php-pgsql
    script:
        - php composer.phar install
        - php composer.phar test
    needs:
        - Check code-style
    only:
        - Setup_CI
